version: '3'
services:
  client:
    image: 'connorethan/multi-client:latest'
    mem_limit: '128m'
    hostname: 'client'
  server:
    image: 'connorethan/multi-server:latest'
    mem_limit: '128m'
    hostname: 'api'
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=$PGDATABASE
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT
  worker:
    image: 'connorethan/multi-worker:latest'
    mem_limit: '128m'
    hostname: 'worker'
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'connorethan/multi-nginx'
    mem_limit: '128m'
    hostname: 'nginx'
    ports:
      - '80:80'
