apiVersion: apps/v1
kind: Deployment
metadata:
  # name object
  name: client-deployment
spec:
  # number of pods to be created
  replicas: 1
  # This selector allows the deployment to identify the pods it creates
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000
