apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  resources:
    requests:
      # kubernetes slices this out of the hard drive when on your local system
      # If on a cloud provider you have many different options
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
